name: "Run Build Dev"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup OSSUTIL
      uses: yizhoumo/setup-ossutil@v2
      with:
        endpoint: ${{ secrets.OSS_ENDPOINT }}
        access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        ossutil-version: 'latest'

    - name: Upload Assets to OSS
      run: |
        ossutil sync apps oss://apps-fit2cloud-com/stable/maxkb --update --delete --force